# Generated by Django 2.0.9 on 2018-12-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=35)),
                ('newsletter', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
