# Generated by Django 2.0.9 on 2018-12-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rio', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_adrink',
            field=models.BooleanField(default=False),
        ),
    ]
